name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build for Raspberry Pi
        run: |
          env GOOS=linux GOARCH=arm GOARM=7 go build -o auto-pi-feeder cmd/auto-pi-feeder/main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: auto-pi-feeder
          path: auto-pi-feeder
